"""Regenerate semantic-view verified-query gold SQL via row-equivalence.

For each failing VQR (``EVAL_AGG_SCORE = 0``) on a given run, run both the
gold SQL (``GROUND_TRUTH``) and the SQL Cortex Analyst actually produced
(``OUTPUT``); if the result rows are equivalent as multisets, the gold can
be safely replaced with Analyst's form (the eval becomes deterministic-pass
without sacrificing analytical correctness). When they diverge, surface a
diff so a human can decide whether to:

  * tighten the question text so Analyst produces the intended SQL,
  * accept Analyst's interpretation as the new gold,
  * or extend the SV (e.g. add a missing metric) so Analyst doesn't have
    to derive logic the gold encodes.

Usage::

    agent-mgmt-regen-sv-gold \\
        --env dev \\
        --sv SEM_STAFFING_ANALYTICS \\
        --run-name PR-52-25465013047_sem_staffing_analytics \\
        --json > regen_report.json

Design notes
------------
* "Row equivalent" = same multiset of rows after sorting columns by name
  and rows lexicographically. Column order and column aliases that differ
  are tolerated; row content must match exactly.
* Both gold and analyst SQL are run with ``LIMIT N`` (default 200) to keep
  the comparison cheap. If a query is naturally non-deterministic
  (``ORDER BY`` only on a tied dimension), this can produce false
  divergences -- callers can ``--limit 0`` to disable the cap.
* Output is structured JSON so a follow-up step can apply the equivalent
  updates to dbt SV source automatically.
"""
from __future__ import annotations

import argparse
import json
import logging
import re
import sys
from dataclasses import asdict, dataclass

from agent_management import setup_logging
from agent_management.evals.sv_scores import fetch_eval_data_with_fallback
from agent_management.utils.config import get_database, load_env_config
from agent_management.utils.snowflake_client import connect

logger = logging.getLogger(__name__)


_REQUEST_ID_COMMENT = re.compile(
    r"\s*--\s*Generated by Cortex Analyst\s*\(request_id:[^)]*\)\s*;?\s*$",
    re.IGNORECASE,
)


def strip_request_id_comment(sql: str | None) -> str:
    """Remove the trailing Cortex Analyst attribution comment so the SQL
    is structurally clean for execution and diffing.
    """
    if not sql:
        return ""
    return _REQUEST_ID_COMMENT.sub("", sql).rstrip().rstrip(";")


def _normalize_row(row: tuple) -> tuple:
    """Make rows hashable + comparable across small numeric jitter.

    Floats are rounded to 6 decimal places (Cortex Analyst's CAST may
    produce slightly different precision than gold), Decimals become
    floats, None becomes a sentinel string so mixed-type rows can sort,
    bytes/other pass through.
    """
    out = []
    for cell in row:
        if cell is None:
            # Sentinel that sorts before any real value but stays distinct
            # from a literal "" or "None" string in the data.
            out.append("\x00__none__")
            continue
        if isinstance(cell, float):
            out.append(round(cell, 6))
            continue
        if hasattr(cell, "as_tuple"):  # decimal.Decimal
            try:
                out.append(round(float(cell), 6))
            except (TypeError, ValueError):
                out.append(str(cell))
            continue
        if isinstance(cell, (int, str, bool)):
            out.append(cell)
            continue
        # Fallback: stringify exotic types (datetime, bytes) so sort works.
        out.append(str(cell))
    return tuple(out)


def _sortable_key(row: tuple) -> tuple:
    """Coerce mixed-type tuples to a sortable form.

    Even after normalization rows can mix str and int -- Python 3 won't
    compare those across types. Stringify everything for sort key only;
    equality still uses the normalized tuple.
    """
    return tuple(str(c) for c in row)


def _column_sorted_rows(columns: list[str], rows: list[tuple]) -> list[tuple]:
    """Sort each row's cells by column-name order so two queries with the
    same columns in different positions still compare equal.
    """
    if not rows:
        return []
    order = sorted(range(len(columns)), key=lambda i: columns[i].upper())
    sorted_columns = [columns[i] for i in order]
    sorted_rows = [tuple(r[i] for i in order) for r in rows]
    normalized = [_normalize_row(r) for r in sorted_rows]
    normalized.sort(key=_sortable_key)
    logger.debug("Column-sorted columns: %s", sorted_columns)
    return normalized


def run_query_sample(
    cur, sql: str, limit: int = 200
) -> tuple[list[str], list[tuple]]:
    """Execute ``sql`` and return (column_names, rows). Caller chooses the
    LIMIT semantics; we add ``LIMIT N`` only if the SQL doesn't already
    have one.
    """
    if limit and " limit " not in sql.lower():
        # Wrap to avoid breaking ORDER BY / set-op semantics.
        wrapped = f"SELECT * FROM ({sql.rstrip(';')}) AS _regen_q LIMIT {limit}"
    else:
        wrapped = sql
    cur.execute(wrapped)
    columns = [col[0] for col in cur.description]
    rows = cur.fetchall()
    return columns, rows


@dataclass
class VQRComparison:
    input_id: str
    question: str
    score: float | None
    gold_sql: str
    analyst_sql: str
    verdict: str  # "equivalent" | "divergent" | "gold_error" | "analyst_error"
    gold_row_count: int | None = None
    analyst_row_count: int | None = None
    gold_columns: list[str] | None = None
    analyst_columns: list[str] | None = None
    error: str | None = None


def compare_vqr(
    cur, gold_sql: str, analyst_sql_raw: str, limit: int
) -> tuple[str, dict]:
    """Run both queries and classify the relationship.

    Returns (verdict, details) where verdict is one of:
        "equivalent"     -- same multiset of rows after column normalization
        "divergent"      -- both ran cleanly but rows differ
        "gold_error"     -- gold SQL raised
        "analyst_error"  -- analyst SQL raised
        "both_error"     -- both raised
    """
    analyst_sql = strip_request_id_comment(analyst_sql_raw)
    details: dict = {}

    gold_cols: list[str] = []
    gold_rows: list[tuple] = []
    analyst_cols: list[str] = []
    analyst_rows: list[tuple] = []

    gold_err = None
    analyst_err = None

    try:
        gold_cols, gold_rows = run_query_sample(cur, gold_sql, limit)
    except Exception as exc:  # noqa: BLE001 - capture, not bubble
        gold_err = str(exc)

    try:
        analyst_cols, analyst_rows = run_query_sample(cur, analyst_sql, limit)
    except Exception as exc:  # noqa: BLE001
        analyst_err = str(exc)

    details["gold_columns"] = gold_cols
    details["analyst_columns"] = analyst_cols
    details["gold_row_count"] = len(gold_rows) if not gold_err else None
    details["analyst_row_count"] = len(analyst_rows) if not analyst_err else None

    if gold_err and analyst_err:
        details["error"] = f"gold={gold_err[:200]} | analyst={analyst_err[:200]}"
        return "both_error", details
    if gold_err:
        details["error"] = f"gold: {gold_err[:300]}"
        return "gold_error", details
    if analyst_err:
        details["error"] = f"analyst: {analyst_err[:300]}"
        return "analyst_error", details

    gold_norm = _column_sorted_rows(gold_cols, gold_rows)
    analyst_norm = _column_sorted_rows(analyst_cols, analyst_rows)

    if gold_norm == analyst_norm:
        return "equivalent", details

    # Surface a small diff to help humans triage divergent cases.
    details["gold_sample"] = gold_norm[:3]
    details["analyst_sample"] = analyst_norm[:3]
    details["gold_only_count"] = len(set(map(tuple, gold_norm)) - set(map(tuple, analyst_norm)))
    details["analyst_only_count"] = len(set(map(tuple, analyst_norm)) - set(map(tuple, gold_norm)))
    return "divergent", details


def regen_failing_vqrs(
    env: str | None,
    sv_name: str,
    run_name: str,
    limit: int = 200,
) -> list[VQRComparison]:
    """For each row with EVAL_AGG_SCORE = 0 in the given run, compare gold
    vs analyst output and return per-VQR verdicts.
    """
    config = load_env_config(env)
    database = get_database(config)
    schema = config["deployment"]["semantic_schema"]

    conn = connect(config)
    cur = conn.cursor()
    cur.execute(f"USE DATABASE {database}")
    cur.execute(f"USE SCHEMA {database}.{schema}")

    try:
        rows, matched_run = fetch_eval_data_with_fallback(
            cur, database, schema, sv_name.upper(), run_name
        )
        logger.info(
            "Fetched %d rows from run=%s (matched %s)",
            len(rows), run_name, matched_run,
        )

        comparisons: list[VQRComparison] = []
        for r in rows:
            score = r.get("EVAL_AGG_SCORE")
            # Only triage failing VQRs. Passing ones are already aligned.
            if score is None or float(score) != 0.0:
                continue

            gold = r.get("GROUND_TRUTH") or ""
            analyst = r.get("OUTPUT") or ""
            verdict, details = compare_vqr(cur, gold, analyst, limit)

            comparisons.append(
                VQRComparison(
                    input_id=r.get("INPUT_ID") or "",
                    question=(r.get("INPUT") or "")[:300],
                    score=float(score),
                    gold_sql=gold,
                    analyst_sql=strip_request_id_comment(analyst),
                    verdict=verdict,
                    gold_row_count=details.get("gold_row_count"),
                    analyst_row_count=details.get("analyst_row_count"),
                    gold_columns=details.get("gold_columns"),
                    analyst_columns=details.get("analyst_columns"),
                    error=details.get("error"),
                )
            )

            logger.info(
                "  [%s] %s -- %d gold rows, %d analyst rows",
                verdict.upper(),
                (r.get("INPUT") or "")[:80],
                details.get("gold_row_count") or 0,
                details.get("analyst_row_count") or 0,
            )

        return comparisons
    finally:
        cur.close()
        conn.close()


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Regenerate semantic-view verified-query gold via row-equivalence"
            " against the SQL Cortex Analyst actually produces."
        )
    )
    parser.add_argument("--env", "-e", help="Environment (dev, qa, prod)")
    parser.add_argument(
        "--sv", required=True,
        help="Semantic view name (e.g. SEM_STAFFING_ANALYTICS)",
    )
    parser.add_argument(
        "--run-name", required=True,
        help="Eval run name (typically PR-NNN-<run_id>_sem_<sv>)",
    )
    parser.add_argument(
        "--limit", type=int, default=200,
        help="Row sample limit (0 to disable)",
    )
    parser.add_argument(
        "--json", dest="json_output", action="store_true",
        help="Emit machine-readable JSON instead of human-readable text",
    )
    parser.add_argument("-v", "--verbose", action="count", default=1)
    args = parser.parse_args()

    setup_logging(args.verbose)

    comparisons = regen_failing_vqrs(
        args.env, args.sv, args.run_name, limit=args.limit
    )

    if args.json_output:
        print(json.dumps([asdict(c) for c in comparisons], indent=2, default=str))
    else:
        if not comparisons:
            logger.info("No failing VQRs found for %s in run %s", args.sv, args.run_name)
            return 0

        print("=" * 78)
        print(f"Regen report: {args.sv} (run={args.run_name})")
        print("=" * 78)
        for c in comparisons:
            print(f"\n[{c.verdict.upper()}] {c.question[:100]}")
            print(f"  gold: {c.gold_row_count} rows / cols {c.gold_columns}")
            print(f"  analyst: {c.analyst_row_count} rows / cols {c.analyst_columns}")
            if c.error:
                print(f"  error: {c.error}")
        print("\n" + "=" * 78)
        equivalent = [c for c in comparisons if c.verdict == "equivalent"]
        divergent = [c for c in comparisons if c.verdict == "divergent"]
        errors = [c for c in comparisons if c.verdict.endswith("_error") or c.verdict == "both_error"]
        print(
            f"Summary: {len(equivalent)} equivalent, {len(divergent)} divergent, "
            f"{len(errors)} error  (out of {len(comparisons)} failing VQRs)"
        )
        if divergent:
            print(
                "\nDivergent VQRs need human triage: tighten question text, "
                "accept analyst form, or add SV metric so analyst doesn't "
                "have to derive the gold's logic."
            )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
