"""Bootstrap dbt seed tables into the RAW schema.

dbt models under ``dbt_ski_resort/models/marts/dimensions/`` reference
``source('raw', 'lifts' | 'locations' | 'products' | 'ticket_types')``.
These four reference tables are NOT generated by ``generate_complete_ski_data.py``
and they are NOT created by DCM. Without them a fresh-env dbt run fails with
"Object 'AM_SKI_RESORT_DEV.RAW.LIFTS' does not exist or not authorized".

This script loads the four CSVs from ``dbt_ski_resort/seeds/`` into
``<SNOWFLAKE_DATABASE>.RAW`` via Snowpark ``write_pandas`` with
``auto_create_table=True, overwrite=True, use_logical_type=True``.

Run locally or from CI (deploy-dev.yml invokes it before ``dbt run``):

    SNOWFLAKE_ACCOUNT=... SNOWFLAKE_USER=... \
    SNOWFLAKE_ROLE=AM_DEPLOY_ROLE_DEV \
    SNOWFLAKE_WAREHOUSE=AM_SKI_RESORT_WH_DEV \
    SNOWFLAKE_DATABASE=AM_SKI_RESORT_DEV \
    SNOWFLAKE_PRIVATE_KEY_PATH=/tmp/snowflake_key.p8 \
    python scripts/bootstrap_raw_seeds.py

Idempotent: overwrite=True always replaces the target.
"""
from __future__ import annotations

import logging
import os
import sys
from pathlib import Path

import pandas as pd
import snowflake.connector
from snowflake.connector.pandas_tools import write_pandas

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
logger = logging.getLogger(__name__)


SEED_ROOT = Path(__file__).resolve().parent.parent / "dbt_ski_resort" / "seeds"
SEEDS: dict[str, str] = {
    "LIFTS": "lift_metadata.csv",
    "LOCATIONS": "location_metadata.csv",
    "PRODUCTS": "product_catalog.csv",
    "TICKET_TYPES": "ticket_type_metadata.csv",
}


def _required(name: str) -> str:
    val = os.environ.get(name)
    if not val:
        raise SystemExit(f"missing env var {name}")
    return val


def main() -> int:
    account = _required("SNOWFLAKE_ACCOUNT")
    user = _required("SNOWFLAKE_USER")
    role = _required("SNOWFLAKE_ROLE")
    warehouse = _required("SNOWFLAKE_WAREHOUSE")
    database = _required("SNOWFLAKE_DATABASE")
    key_path = _required("SNOWFLAKE_PRIVATE_KEY_PATH")
    # Always write into RAW. We intentionally do NOT honor SNOWFLAKE_SCHEMA
    # here because this script owns the target: reference seeds must land
    # in RAW for dbt ``source('raw', ...)`` refs to resolve.
    schema = "RAW"

    logger.info("bootstrap seeds -> %s.%s (role=%s, wh=%s)",
                database, schema, role, warehouse)

    conn = snowflake.connector.connect(
        account=account,
        user=user,
        private_key_file=key_path,
        role=role,
        warehouse=warehouse,
        authenticator="SNOWFLAKE_JWT",
    )
    try:
        cur = conn.cursor()
        cur.execute(f"USE WAREHOUSE {warehouse}")
        cur.execute(f"USE DATABASE {database}")
        cur.execute(f"USE SCHEMA {database}.{schema}")
        for table, filename in SEEDS.items():
            path = SEED_ROOT / filename
            if not path.exists():
                logger.error("missing seed file: %s", path)
                return 2
            df = pd.read_csv(path)
            df.columns = df.columns.str.upper()
            logger.info("  %s: %d rows from %s", table, len(df), path.name)
            success, nchunks, nrows, _ = write_pandas(
                conn,
                df,
                table_name=table,
                database=database,
                schema=schema,
                auto_create_table=True,
                overwrite=True,
                quote_identifiers=False,
                use_logical_type=True,
            )
            if not success:
                logger.error("write_pandas returned failure for %s", table)
                return 3
            logger.info("    wrote %d rows in %d chunk(s)", nrows, nchunks)
        logger.info("seed bootstrap OK")
        return 0
    finally:
        conn.close()


if __name__ == "__main__":
    sys.exit(main())
